//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteLab.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteLab.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOTELAB: Lab pool {0} is full. There are not more available computers..
        /// </summary>
        public static string LabPoolIsFullEmailMessage {
            get {
                return ResourceManager.GetString("LabPoolIsFullEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LoginFormPassword {
            get {
                return ResourceManager.GetString("LoginFormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me?.
        /// </summary>
        public static string LoginFormRememberMe {
            get {
                return ResourceManager.GetString("LoginFormRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name:.
        /// </summary>
        public static string LoginFormUserName {
            get {
                return ResourceManager.GetString("LoginFormUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen mode id:i:2
        ///desktopwidth:i: {0} 
        ///desktopheight:i: {1}
        ///session bpp:i:32
        ///winposstr:s:0,1,614,156,1654,963
        ///full address:s: {2}
        ///username:s: {3}
        ///compression:i:1
        ///keyboardhook:i:2
        ///audiomode:i:0
        ///redirectprinters:i:1
        ///redirectcomports:i:0
        ///redirectsmartcards:i:0
        ///redirectclipboard:i:1
        ///redirectposdevices:i:0
        ///redirectdrives:i:1
        ///drivestoredirect: s()
        ///displayconnectionbar:i:1
        ///pinconnectionbar:i:1
        ///autoreconnection enabled:i:1
        ///authentication level:i:0
        ///prompt for credentials:i:0
        ///negotiate security [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RdpFileSettings {
            get {
                return ResourceManager.GetString("RdpFileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOTELAB: Reboot of computer {0} failed.
        /// </summary>
        public static string RebootFailedEmailMessage {
            get {
                return ResourceManager.GetString("RebootFailedEmailMessage", resourceCulture);
            }
        }
    }
}
