//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteLab.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        public string Database {
            get {
                return ((string)(this["Database"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IST-Users-ITServices")]
        public string AdministratorADGroup {
            get {
                return ((string)(this["AdministratorADGroup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ad.syr.edu")]
        public string ActiveDirectoryDNSDomain {
            get {
                return ((string)(this["ActiveDirectoryDNSDomain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp-host.syr.edu")]
        public string SmtpServer {
            get {
                return ((string)(this["SmtpServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("remotelabadmin@syr.edu")]
        public string SmtpMessageFromAddress {
            get {
                return ((string)(this["SmtpMessageFromAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AD")]
        public string ActiveDirectoryDomain {
            get {
                return ((string)(this["ActiveDirectoryDomain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NetID")]
        public string LoginFormUsernameLabel {
            get {
                return ((string)(this["LoginFormUsernameLabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Password")]
        public string LoginFormPasswordLabel {
            get {
                return ((string)(this["LoginFormPasswordLabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.youtube.com/embed/fyM2OHUS6O4?autoplay=1")]
        public string RemoteLabIntroVideoLink {
            get {
                return ((string)(this["RemoteLabIntroVideoLink"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://answers.syr.edu/display/ischool/iSchool+Remote+Lab")]
        public string OfficialDocumentationLink {
            get {
                return ((string)(this["OfficialDocumentationLink"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://support.microsoft.com/kb/2592687")]
        public string WindowsClientDownload {
            get {
                return ((string)(this["WindowsClientDownload"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://itunes.apple.com/us/app/microsoft-remote-desktop/id715768417?mt=12")]
        public string MacClientDownload {
            get {
                return ((string)(this["MacClientDownload"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 148, 233, 7, 112, 207, 116, 14, 177, 66, 198, 200, 41, 180, 156, 143, 151, 2" +
            "26, 75, 247, 115, 68, 85, 107, 143, 156, 5, 226, 191, 225, 247, 162")]
        public string EncryptionKeyForPasswords {
            get {
                return ((string)(this["EncryptionKeyForPasswords"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          screen mode id:i:2\r\n          desktopwidth:i: {0}\r\n          desktoph" +
            "eight:i: {1}\r\n          session bpp:i:32\r\n          winposstr:s:0,1,614,156,1654" +
            ",963\r\n          full address:s: {2}\r\n          username:s: {3}\r\n          compre" +
            "ssion:i:1\r\n          keyboardhook:i:2\r\n          audiomode:i:0\r\n          redire" +
            "ctprinters:i:1\r\n          redirectcomports:i:0\r\n          redirectsmartcards:i:0" +
            "\r\n          redirectclipboard:i:1\r\n          redirectposdevices:i:0\r\n          r" +
            "edirectdrives:i:1\r\n          drivestoredirect: s()\r\n          displayconnectionb" +
            "ar:i:1\r\n          pinconnectionbar:i:1\r\n          autoreconnection enabled:i:1\r\n" +
            "          authentication level:i:0\r\n          prompt for credentials:i:0\r\n      " +
            "    negotiate security layer:i:1\r\n          remoteapplicationmode:i:0\r\n         " +
            " alternate shell:s:\r\n          shell working directory:s:\r\n          disable wal" +
            "lpaper:i:1\r\n          disable full window drag:i:0\r\n          allow desktop comp" +
            "osition:i:1\r\n          allow font smoothing:i:1\r\n          disable menu anims:i:" +
            "1\r\n          disable themes:i:0\r\n          disable cursor setting:i:0\r\n         " +
            " bitmapcachepersistenable:i:1\r\n          gatewayhostname:s:\r\n          gatewayus" +
            "agemethod:i:0\r\n          gatewaycredentialssource:i:4\r\n          gatewayprofileu" +
            "sagemethod:i:0\r\n          promptcredentialonce:i:1\r\n          use multimon:i:0\r\n" +
            "          audiocapturemode:i:0\r\n          videoplaybackmode:i:1\r\n          conne" +
            "ction type:i:6\r\n          redirectdirectx:i:1\r\n          use redirection server " +
            "name:i:0\r\n          devicestoredirect:s:*\r\n          smart sizing:i:1\r\n        ")]
        public string RdpFileSettings {
            get {
                return ((string)(this["RdpFileSettings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          on error resume next\r\n          dim connstr, remotepowershelluser, po" +
            "olName\r\n          connstr = \"{0}\"\r\n          remotepowershelluser = \"{1}\"\r\n     " +
            "     poolName = \"{2}\"\r\n        ")]
        public string RemoteLabSettingsFileContent {
            get {
                return ((string)(this["RemoteLabSettingsFileContent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int DashboardMaxEvents {
            get {
                return ((int)(this["DashboardMaxEvents"]));
            }
        }
    }
}
